/*
 * This file is part of paged (https://paged.media).
 *
 * paged is free software: you may redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License, version 3, as published by
 * the Free Software Foundation, OR under the Paged Media Enterprise License
 * (PMEL), a commercial license available from And The Next GmbH. Full
 * copyright and license information is available in LICENSE.md, distributed
 * with this source code.
 *
 * paged is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the licenses for details.
 *
 *  @copyright  Copyright (c) And The Next GmbH
 *  @license    AGPL-3.0-only OR Paged Media Enterprise License (PMEL)
 */

/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * This file is part of paged (https://paged.media) and is additionally
 * available under the Paged Media Enterprise License (PMEL). Full
 * copyright and license information is available in LICENSE.md which is
 * distributed with this source code.
 *
 *  @copyright  Copyright (c) And The Next GmbH
 *  @license    MPL-2.0 OR Paged Media Enterprise License (PMEL)
 */

//! Registry-driven dispatch (spec §12.2.1): the dispatch table is
//! generated FROM `registry/kernels.yaml` — an implementation without a
//! registry row does not get a dispatch entry, so unregistered
//! operations are unreachable by construction. The conformance suite
//! additionally asserts the reverse direction (no orphan `KernelDef`
//! statics outside the registry).
//!
//! The YAML is hand-parsed for exactly the two keys this script needs
//! (`id`, `rust_path`); the full row schema (class, tolerance, oracle,
//! provenance, tests) is consumed by the conformance gate, not here.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let registry_path = Path::new("../registry/kernels.yaml");
    println!("cargo:rerun-if-changed=../registry/kernels.yaml");

    let mut rows: Vec<(String, String)> = Vec::new();
    if registry_path.exists() {
        let text = std::fs::read_to_string(registry_path).expect("read registry/kernels.yaml");
        let mut current_id: Option<String> = None;
        for line in text.lines() {
            let trimmed = line.trim();
            if let Some(id) = trimmed.strip_prefix("- id:") {
                current_id = Some(id.trim().to_string());
            } else if let Some(path) = trimmed.strip_prefix("rust_path:") {
                let id = current_id
                    .clone()
                    .expect("registry/kernels.yaml: rust_path before id");
                rows.push((id, path.trim().to_string()));
            }
        }
    }

    let mut out = String::new();
    out.push_str("// GENERATED by build.rs from registry/kernels.yaml — do not edit.\n");
    writeln!(
        out,
        "static REGISTRY_TABLE: [&crate::KernelDef; {}] = [",
        rows.len()
    )
    .unwrap();
    for (id, path) in &rows {
        writeln!(out, "    // {id}\n    &crate::{path},").unwrap();
    }
    out.push_str("];\n\n");
    out.push_str(
        "/// The registry-driven dispatch table (spec §12.2.1).\n\
         pub fn registry() -> &'static [&'static crate::KernelDef] {\n    &REGISTRY_TABLE\n}\n",
    );

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("registry_gen.rs");
    std::fs::write(dest, out).expect("write registry_gen.rs");
}
