import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/**
 * The wasm surface is a contract between two languages that nothing
 * type-checks.
 *
 * `engine.ts` declares `interface ImageWasmModule` — a hand-written TS
 * description of a foreign module. TypeScript believes it. The Rust
 * side exports through `#[wasm_bindgen]`, and an export is never called
 * from Rust, so forgetting the attribute is not a compile error: it is
 * a dead-code warning, and the function silently does not appear on the
 * module at all.
 *
 * That happened. Ten kernel entry points shipped declared-but-absent,
 * and every one of the 193 unit tests stayed green throughout, because
 * they mock the engine — a mock satisfies the interface by
 * construction, so the suite could not see the gap however hard it
 * looked.
 *
 * `#[deny(dead_code)]` on `mod wasm` closes that direction at compile
 * time and is the primary gate. This closes the OTHER direction, which
 * the compiler cannot see: TS naming a function Rust never had. A typo
 * in the interface is invisible until a user clicks the button.
 *
 * The oracle is `image_js.d.ts` — generated BY wasm-bindgen from the
 * real exports, so it cannot drift from the artifact it ships beside.
 */
const WASM_DTS = fileURLToPath(
  new URL("../../manifest/wasm/image_js.d.ts", import.meta.url),
);
const ENGINE_TS = fileURLToPath(new URL("../src/engine.ts", import.meta.url));

/**
 * wasm-bindgen's `--target web` glue also exports its init machinery,
 * which `ImageWasmModule` deliberately does not model. These are not
 * kernel entry points and their absence from the interface is correct.
 */
const INIT_EXPORTS = new Set(["default", "initSync", "init"]);

/**
 * Exports that are deliberately not on the TS interface, each with the
 * reason it is not simply dead weight.
 *
 * An allowlist is only honest if every entry has to justify itself, so
 * these carry the argument rather than just the name. Deleting an entry
 * is how you propose that the export should now be wired or removed.
 */
const UNMODELLED_ON_PURPOSE = new Map([
  [
    "image_tile_rgba8_level",
    // Engine B's mip-pyramid tile window (landed 4cbe46f with the CMYK
    // ingest cast). Its level-0 twin `image_tile_rgba8` IS wired, in
    // decode-worker.ts. This one has no TS caller because there is
    // nothing yet to call it: the tile provider fetches the whole image
    // at its natural extent, so no LOD is ever requested. Wiring it
    // needs the HOST to ask for a level, which is C-1 Stage-B territory
    // (deferred by ADR-018 pending a core external-texture path).
    // Waiting on a consumer, not forgotten — but it does cost bytes
    // against the 100 MB app-wide budget until that consumer exists.
    "no LOD consumer until C-1 Stage-B (ADR-018)",
  ],
]);

function declaredInTs(): string[] {
  const src = readFileSync(ENGINE_TS, "utf8");
  const block = /export interface ImageWasmModule \{(.*?)\n\}/s.exec(src);
  if (!block) throw new Error("ImageWasmModule interface not found in engine.ts");
  return [...block[1].matchAll(/^ {2}([a-z_][A-Za-z0-9_]*)\(/gm)].map((m) => m[1]);
}

function exportedByWasm(): string[] {
  const dts = readFileSync(WASM_DTS, "utf8");
  return [...dts.matchAll(/^export function ([A-Za-z0-9_]+)\(/gm)].map((m) => m[1]);
}

// The artifact is gitignored and built by scripts/build-wasm.sh, so it
// is present locally and in the publish lane but not in the plain
// vitest lane. Skip LOUDLY rather than fail: a red that only means
// "you did not build the wasm" trains people to ignore this file.
const built = existsSync(WASM_DTS);
const gate = built ? describe : describe.skip;

if (!built) {
  console.warn(
    "[wasm-surface] SKIPPED — manifest/wasm/image_js.d.ts absent. " +
      "Run scripts/build-wasm.sh to exercise this gate. The compile-time " +
      "half (deny(dead_code) on mod wasm) still runs in the Rust lane.",
  );
}

gate("the TS/wasm surface contract", () => {
  it("declares nothing the wasm module does not export", () => {
    const exported = new Set(exportedByWasm());
    const missing = declaredInTs().filter(
      (n) => !exported.has(n) && !INIT_EXPORTS.has(n),
    );
    // Named individually so the failure says WHICH call would land on
    // undefined at runtime, rather than just that a count disagreed.
    expect(missing).toEqual([]);
  });

  it("exports nothing the TS interface has not modelled", () => {
    const declared = new Set(declaredInTs());
    const unmodelled = exportedByWasm().filter(
      (n) =>
        !declared.has(n) &&
        !INIT_EXPORTS.has(n) &&
        !UNMODELLED_ON_PURPOSE.has(n),
    );
    // This direction is a weaker failure — an unreachable export costs
    // wasm bytes against the 100 MB app-wide budget rather than breaking a call —
    // but it is the signal that a kernel was built and never wired,
    // which is its own way of shipping nothing.
    expect(unmodelled).toEqual([]);
  });

  it("agrees on the entry points for every kernel the panel can reach", () => {
    // A regression-specific assertion: these ten are the exact set that
    // shipped declared-but-absent. Keeping them named means a repeat of
    // that particular mistake fails with the history attached.
    const regressed = [
      "apply_emboss",
      "apply_find_edges",
      "apply_lens_blur",
      "apply_mosaic",
      "apply_motion_blur",
      "apply_offset",
      "apply_radial_blur",
      "apply_reduce_noise",
      "apply_selective_color",
      "apply_smart_sharpen",
    ];
    const exported = new Set(exportedByWasm());
    expect(regressed.filter((n) => !exported.has(n))).toEqual([]);
  });
});
